Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

#    config.vm.define "mysqldb" do |mysql|
#      mysql.vm.network "private_network", ip: "192.168.50.4"
#    
#      mysql.vm.synced_folder "./configs", "/configs"
#      mysql.vm.synced_folder ".", "/vagrant", disabled: true
#    
#      mysql.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
#      mysql.vm.provision "shell", path: "script_curso_vagrant_mysql.sh"
#      mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
#      mysql.vm.provision "shell", inline: "service mysql restart"
#    end

    config.vm.define "phpweb" do |phpweb|
      phpweb.vm.network "private_network", ip: "192.168.50.5"
      phpweb.vm.network "forwarded_port", guest: 8080, host: 8080

      phpweb.vm.provision "shell", path: "script_curso_vagrant_php.sh"
      phpweb.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "./configs/manifests"
        puppet.manifest_file = "web.pp"
      end
    end

    config.vm.define "mysqlserver" do |mysqlserver|
      mysqlserver.vm.network "private_network", ip: "192.168.50.6"

      mysqlserver.vm.provision "shell", inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"
    end

    config.vm.define "ansible" do |ansible|
      ansible.vm.network "private_network", ip: "192.168.50.7"

      ansible.vm.provision "shell", path: "script_curso_vagrant_ansible.sh"
    end

    config.vm.define "memcached" do |memcached|
      memcached.vm.box = "centos/7"

      memcached.vm.network "private_network", ip: "192.168.50.8"

      memcached.vm.provider "virtualbox" do |vb|
        vb.name = "centos7_memcached"
        vb.memory = 512
        vb.cpus = 1
      end
    end

    config.vm.define "dockerhost" do |dockerhost|
      dockerhost.vm.network "private_network", ip: "192.168.50.9"

      dockerhost.vm.provision "shell", path: "script_curso_vagrant_dockerhost.sh"
      dockerhost.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu_dockerhost"
        vb.memory = 512
        vb.cpus = 1
      end
    end

  end